### ISSUE TITLE
Fix Navbar for Mobile

### ISSUE THREAD

**Issue by Mridul2820** [Mridul2820/git-o-get#12]
## How to recreate the issue
If you resize the screen to `400px` This issue will appear
## Issue Screenshot
![Screenshot 2022-10-06 001150](https://user-images.githubusercontent.com/43516008/194137574-91c4a213-aa99-459f-b667-70dfd2020583.jpg)
## Probable Fix
Reduce the width of search bar

**Comment by Anupamgupt** [comment]
Can I work On this issue?

**Comment by Mridul2820** [comment]
@Anupamgupt Sure
