### ISSUE TITLE
Responsive Social Card for Mobile - Card is having extra height for mobile

### ISSUE THREAD

**Issue by Mridul2820** [Mridul2820/git-o-get#13]
## How to recreate the issue
If you resize the screen to `400px` This issue will appear
## Issue 
![Screenshot 2022-10-06 001727](https://user-images.githubusercontent.com/43516008/194138449-7a6711e9-3e57-479e-8d71-a23b37ff83da.jpg)
Screenshot

**Comment by josecollado** [comment]
would like to work on this- how did you want to fix this? please assign me

**Comment by Mridul2820** [comment]
If you search your profile in the Mobile version you will get an extra space in the bottom of `Social Card`, that's the issue.
