### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by BrunoLagoa** [Mridul2820/git-o-get#16]
Project was a lot of show! it would be nice to have a dark mode

**Comment by Mridul2820** [comment]
Yeah, that will be a nice feature

**Comment by ziarparvaiz** [comment]
✋😊 I want to do dark mode @Mridul2820 please assign me this issue

**Comment by BrunoLagoa** [comment]
> ✋😊 I want to do dark mode @Mridul2820 please assign me this issue

nice!

**Comment by ziarparvaiz** [comment]
@Mridul2820  I used GitHub color palette, how is it? but I couldn't activate this social card component, I did it in cloudinary settings but it didn't come.

![git-o-get](https://user-images.githubusercontent.com/50423368/194678373-3cceedb2-d128-4800-8007-388a9f24541c.gif)

**Comment by BrunoLagoa** [comment]
Nice

**Comment by ziarparvaiz** [comment]
> @Mridul2820 I used GitHub color palette, how is it? but I couldn't activate this social card component, I did it in cloudinary settings but it didn't come.
> 
> ![git-o-get](https://user-images.githubusercontent.com/50423368/194678373-3cceedb2-d128-4800-8007-388a9f24541c.gif)

@Mridul2820

**Comment by Mridul2820** [comment]
Hi @BrunoLagoa sorry for the late reply. This looks really awesome. 
Can you recheck if this is unchecked?

settings > security > Restricted media types > Fetched URL

![Screenshot from 2022-10-10 12-19-00](https://user-images.githubusercontent.com/43516008/194811480-2682f1c4-5d66-4d58-86fe-dc1953367d57.png)

**Comment by ziarparvaiz** [comment]
@Mridul2820 Yeah its checked
![Screenshot 2022-10-10 at 09-55-10 Cloudinary Management Console - Settings](https://user-images.githubusercontent.com/50423368/194812215-f9ef3772-73b6-4004-85bb-7fadcfc0fd8b.png)

**Comment by Mridul2820** [comment]
Uncheck this one.. may be this will fix

**Comment by ziarparvaiz** [comment]
Unfortunately it didn't work. I'll send a PR until late, we'll see what do you think?

**Comment by Mridul2820** [comment]
Yeah that will be great
