### ISSUE TITLE
Bugs in dark theme

### ISSUE THREAD

**Issue by xnatsuk** [Mridul2820/git-o-get#24]
Currently the dark theme has a few minor bugs:

- When switching to dark theme, some elements appear to slightly move/change size
- The Contribution Graph displays 0 contributions in white instead of gray like github

I wish to fix them, please tag this issue and assign it to me.

**Comment by codeansh20** [comment]
Sir I can do this task
But can u please tell me in which project you are facing problem

**Comment by Mridul2820** [comment]
> Sir I can do this task But can u please tell me in which project you are facing problem

Hi @codeansh20 , You can work on any issue from [here](https://github.com/Mridul2820/git-o-get/issues)
