### ISSUE TITLE
After a search from the navbar loader still stays even after the data load

### ISSUE THREAD

**Issue by Mridul2820** [Mridul2820/git-o-get#27]
Issue Screenshot

![Screenshot 2022-10-19 225420](https://user-images.githubusercontent.com/43516008/196762015-9d6bb59d-4762-42a3-a1be-929f0abb15f1.jpg)

**Comment by zainbinfurqan** [comment]
@Mridul2820  Hi can i work on it?

**Comment by Mridul2820** [comment]
> @Mridul2820  Hi can i work on it?

Sure

**Comment by zainbinfurqan** [comment]
Assign it to me please @Mridul2820
