### ISSUE TITLE
Tooltip Show on each day of Contribution Heatmap

### ISSUE THREAD

**Issue by Mridul2820** [Mridul2820/git-o-get#38]
The tooltip on the heatmap is not working

**Comment by Diwanshumidha** [comment]
Hello @Mridul2820,

i work on this Issue Can you assign it to me ?

**Comment by Diwanshumidha** [comment]
Yeah Task is completed 
Can I raise PR on October 1st so that our contribution count hectoberfest

**Comment by Mridul2820** [comment]
Yeah Sure @Diwanshumidha
