### ISSUE TITLE
Show White boxes for the days where no contribution were made in the Heatmap

### ISSUE THREAD

**Issue by Mridul2820** [Mridul2820/git-o-get#40]
Currently, In the heatmap, all the boxes are green even if no contribution is available on a day. It will be great if we Show White boxes for the days where no contribution were made in the Heatmap

**Comment by MacMillon-VS** [comment]
Hello @Mridul2820,
 
Could you please assign this task to me so that I can get started?

Thank you!

**Comment by MacMillon-VS** [comment]
Hello @Mridul2820 
I'm trying to recreate this issue but it already showing white box for the days where no contribution were made in the Heatmap.
Could you please elaborate the issue?

![image](https://github.com/Mridul2820/git-o-get/assets/93966956/dc1a6f87-31db-41f2-925b-ee8e9f07686a)
![image](https://github.com/Mridul2820/git-o-get/assets/93966956/9c85a399-19ec-41eb-9ba9-b35e3f5ed04c)

**Comment by Mridul2820** [comment]
Hi @MacMillon-VS 

I searched your username in the app [MacMillon-VS](https://git-o-get.mridul.tech/user/MacMillon-VS)

This is what is showing me

<img width="893" alt="image" src="https://github.com/Mridul2820/git-o-get/assets/43516008/095a1fc3-0019-478e-86d8-71752d51491d">
<img width="886" alt="image" src="https://github.com/Mridul2820/git-o-get/assets/43516008/7fea7b28-65a5-4f42-ac3a-23a480d00272">

Can you check in this URL?

**Comment by MacMillon-VS** [comment]
@Mridul2820  I got how this happening. This is due to our system theme settings. I can solve it.
