### ISSUE TITLE
Remove Scrollbar in Pinned Repository Cards for Desktop

### ISSUE THREAD

**Issue by Mridul2820** [Mridul2820/git-o-get#43]
For Desktop Remove Scrollbar in Pinned Repository Cards. For Mobile It  should remain the same

<img width="1403" alt="image" src="https://github.com/Mridul2820/git-o-get/assets/43516008/19d06cff-2822-4643-8a3e-ac90bce00148">

**Comment by MacMillon-VS** [comment]
@Mridul2820 Please assign this issue to me.

**Comment by RacHiT101** [comment]
hey @Mridul2820 can I work on this issue

**Comment by MacMillon-VS** [comment]
Hello @Mridul2820. I have noticed another issue in this pinned repository cards. That is, if the description is larger, then it's overflowing in that card.  I know how to fix it. Shall I solve that also with this issue? 
Please refer the screenshot
![image](https://github.com/Mridul2820/git-o-get/assets/93966956/49d91c79-3c4e-49e7-b684-e4e91f14a81c)

**Comment by Mridul2820** [comment]
Great Finding. Please raise an Issue and If you can fix it that will be awesome

**Comment by RacHiT101** [comment]
Can I fix this @Mridul2820

**Comment by MacMillon-VS** [comment]
Ok sure. I will raise new issue for it. And if you are ok I will fix that with this current issue. It's one line change

**Comment by Mridul2820** [comment]
Sure @MacMillon-VS . 

@RacHiT101 there are other issues also you can pick them as well
