### ISSUE TITLE
Add Instagram and Linkedin Links in the User Card

### ISSUE THREAD

**Issue by Mridul2820** [Mridul2820/git-o-get#44]
There is already a User Twitter link. Add Instagram and LinkedIn links after that

<img width="434" alt="image" src="https://github.com/Mridul2820/git-o-get/assets/43516008/5113baf0-805c-4d37-a319-f24c433bba0d">

**Comment by Harsh97x** [comment]
I'll work on it, please assign me to it. Thanks

**Comment by Mridul2820** [comment]
Hi @Harsh97x any update on the issue?

**Comment by Diwanshumidha** [comment]
@Mridul2820 
I have resolved this issue can you please sign this issue to me

**Comment by Diwanshumidha** [comment]
<img width="301" alt="image" src="https://github.com/Mridul2820/git-o-get/assets/125127610/cc61441f-3d56-4b8d-bc36-bf892dfc3b83">

Will this work???

**Comment by Mridul2820** [comment]
This looks awesome 

Can you just change the LinkedIn a bit and remove the `company/`
