### ISSUE TITLE
Profile Page is Not working after copy share link from social card

### ISSUE THREAD

**Issue by Diwanshumidha** [Mridul2820/git-o-get#46]
When We copy share link in social card 'https://git-o-get.mridul.tech/profile/Diwanshumidha' the link is missing and showing 404 page 

I Would like to add this feature

**Comment by Mridul2820** [comment]
The actual URL is https://git-o-get.mridul.tech/user/Diwanshumidha

The slug is `/user/[slug]` not `/profile/[slug]`

**Comment by Mridul2820** [comment]
Thanks for raising the issue. Please raise a PR after fixing the issue

**Comment by Diwanshumidha** [comment]
@Mridul2820  
can you please explain me what should be there in Profile/[id] page like all the requirements

**Comment by Mridul2820** [comment]
It will be only `/user/[slug]`

**Comment by Diwanshumidha** [comment]
So Sharecard will copy https://git-o-get.mridul.tech/user/adrianhajdin instead of https://git-o-get.mridul.tech/profile/adrianhajdin
